// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwiumAPBD.Models;

namespace kolokwiumAPBD.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20200620165430_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolokwiumAPBD.Models.Artist", b =>
                {
                    b.Property<int>("IdArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdArtist");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            IdArtist = 1,
                            Nickname = "Slash"
                        },
                        new
                        {
                            IdArtist = 2,
                            Nickname = "Axel"
                        },
                        new
                        {
                            IdArtist = 3,
                            Nickname = "Bruno"
                        },
                        new
                        {
                            IdArtist = 4,
                            Nickname = "Mick"
                        });
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Artist_Event", b =>
                {
                    b.Property<int>("IdArtist")
                        .HasColumnType("int");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistIdArtist")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventIdEvent")
                        .HasColumnType("int");

                    b.HasKey("IdArtist", "IdEvent");

                    b.HasIndex("ArtistIdArtist");

                    b.HasIndex("EventIdEvent");

                    b.HasIndex("IdEvent");

                    b.ToTable("Artist_Events");

                    b.HasData(
                        new
                        {
                            IdArtist = 1,
                            IdEvent = 1,
                            DateTime = new DateTime(2020, 7, 11, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtist = 2,
                            IdEvent = 1,
                            DateTime = new DateTime(2020, 7, 11, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtist = 2,
                            IdEvent = 2,
                            DateTime = new DateTime(2020, 7, 23, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtist = 3,
                            IdEvent = 2,
                            DateTime = new DateTime(2020, 7, 23, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtist = 4,
                            IdEvent = 3,
                            DateTime = new DateTime(2020, 8, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtist = 3,
                            IdEvent = 3,
                            DateTime = new DateTime(2020, 8, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            EndDate = new DateTime(2020, 7, 11, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wieczor muzyczny WWa",
                            StartDate = new DateTime(2020, 7, 11, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 2,
                            EndDate = new DateTime(2020, 7, 23, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Go Rock",
                            StartDate = new DateTime(2020, 7, 23, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 3,
                            EndDate = new DateTime(2020, 8, 6, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Warsaw Festival",
                            StartDate = new DateTime(2020, 8, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Event_Organiser", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdOrganiser")
                        .HasColumnType("int");

                    b.Property<int?>("EventIdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("OrganiserIdOrganiser")
                        .HasColumnType("int");

                    b.HasKey("IdEvent", "IdOrganiser");

                    b.HasIndex("EventIdEvent");

                    b.HasIndex("IdOrganiser");

                    b.HasIndex("OrganiserIdOrganiser");

                    b.ToTable("Event_Organisers");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            IdOrganiser = 1
                        },
                        new
                        {
                            IdEvent = 2,
                            IdOrganiser = 1
                        });
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Organiser", b =>
                {
                    b.Property<int>("IdOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdOrganiser");

                    b.ToTable("Organisers");

                    b.HasData(
                        new
                        {
                            IdOrganiser = 1,
                            Name = "Evenea"
                        },
                        new
                        {
                            IdOrganiser = 2,
                            Name = "GoLIve"
                        });
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Artist_Event", b =>
                {
                    b.HasOne("kolokwiumAPBD.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistIdArtist");

                    b.HasOne("kolokwiumAPBD.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventIdEvent");

                    b.HasOne("kolokwiumAPBD.Models.Artist", null)
                        .WithMany("Artist_Events")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwiumAPBD.Models.Event", null)
                        .WithMany("Artist_Events")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kolokwiumAPBD.Models.Event_Organiser", b =>
                {
                    b.HasOne("kolokwiumAPBD.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventIdEvent");

                    b.HasOne("kolokwiumAPBD.Models.Event", null)
                        .WithMany("Event_Organisers")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwiumAPBD.Models.Organiser", null)
                        .WithMany("Event_Organisers")
                        .HasForeignKey("IdOrganiser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwiumAPBD.Models.Organiser", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserIdOrganiser");
                });
#pragma warning restore 612, 618
        }
    }
}
